/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab3;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ANKIT
 */
public class Client_GUI extends javax.swing.JFrame {
    private Client client;
    /**
     * Creates new form Client_GUI
     */
    public Client_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tabbedPane_main = new javax.swing.JTabbedPane();
        panel_server = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tf_server_ip = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_server_port = new javax.swing.JTextField();
        bun_con_server = new javax.swing.JButton();
        l_con_status = new javax.swing.JLabel();
        bun_disconnect = new javax.swing.JButton();
        panel_login = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_un = new javax.swing.JTextField();
        bun_login = new javax.swing.JButton();
        bun_register = new javax.swing.JButton();
        bun_logout = new javax.swing.JButton();
        l_login_msg = new javax.swing.JLabel();
        pf_pass = new javax.swing.JTextField();
        panel_add_friend = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf_nameToAdd = new javax.swing.JTextField();
        bun_add = new javax.swing.JButton();
        l_status_add = new javax.swing.JLabel();
        panel_get_ip = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tf_nameForIP = new javax.swing.JTextField();
        bun_getIP = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tf_ip_getIP = new javax.swing.JTextField();
        l_getIP_status = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panel_users_list = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_ulist = new javax.swing.JTextArea();
        panel_friends_list = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_flist = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabPanel_chat = new javax.swing.JTabbedPane();
        panel_gchat_tab1 = new javax.swing.JPanel();
        bun_gchat_tab1_add = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        ta_gchat_tab1_log = new javax.swing.JTextArea();
        tf_gchat_tab1_msg = new javax.swing.JTextField();
        bun_gchat_tab1_send = new javax.swing.JButton();
        l_gchat_tab1_status = new javax.swing.JLabel();
        ta_gchat_tab1_group = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tf_p2pchat_name = new javax.swing.JTextField();
        bun_p2pchat_getip = new javax.swing.JButton();
        l_p2pchat_status = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        ta_p2pchat_log = new javax.swing.JTextArea();
        tf_p2pchat_msg = new javax.swing.JTextField();
        bun_p2pchat_send = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane9.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabbedPane_main.setBackground(new java.awt.Color(204, 204, 255));

        panel_server.setBackground(new java.awt.Color(102, 102, 255));
        panel_server.setMaximumSize(new java.awt.Dimension(327, 327));
        panel_server.setPreferredSize(new java.awt.Dimension(308, 250));

        jLabel5.setText("server IP");

        tf_server_ip.setText("localhost");

        jLabel14.setText("port");

        tf_server_port.setText("1500");

        bun_con_server.setText("connect");
        bun_con_server.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bun_con_serverActionPerformed(evt);
            }
        });

        l_con_status.setText("status");

        bun_disconnect.setText("disconnect");
        bun_disconnect.setIconTextGap(1);
        bun_disconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bun_disconnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_serverLayout = new javax.swing.GroupLayout(panel_server);
        panel_server.setLayout(panel_serverLayout);
        panel_serverLayout.setHorizontalGroup(
            panel_serverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_serverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_serverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_con_status, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_serverLayout.createSequentialGroup()
                        .addGroup(panel_serverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_serverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(bun_con_server, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(panel_serverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_server_port, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_server_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bun_disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        panel_serverLayout.setVerticalGroup(
            panel_serverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_serverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_serverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_server_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_serverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_server_port, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_serverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bun_con_server)
                    .addComponent(bun_disconnect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_con_status, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        tabbedPane_main.addTab("server", panel_server);

        panel_login.setBackground(new java.awt.Color(255, 255, 204));
        panel_login.setForeground(new java.awt.Color(255, 255, 51));

        jLabel2.setText("username");

        jLabel3.setText("password");

        bun_login.setText("login");
        bun_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bun_loginActionPerformed(evt);
            }
        });

        bun_register.setText("register");
        bun_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bun_registerActionPerformed(evt);
            }
        });

        bun_logout.setText("logout");
        bun_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bun_logoutActionPerformed(evt);
            }
        });

        l_login_msg.setBackground(new java.awt.Color(0, 153, 0));
        l_login_msg.setForeground(new java.awt.Color(51, 51, 51));
        l_login_msg.setText("status");

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bun_register)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_login_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_loginLayout.createSequentialGroup()
                                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tf_un)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(bun_login))
                                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_loginLayout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel3))
                                    .addGroup(panel_loginLayout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(pf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(bun_logout)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_un, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bun_login)
                    .addComponent(bun_register))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bun_logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_login_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        tabbedPane_main.addTab("login", panel_login);

        panel_add_friend.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setText("friend's name");

        tf_nameToAdd.setText("friend");

        bun_add.setText("add to list");
        bun_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bun_addActionPerformed(evt);
            }
        });

        l_status_add.setText("status");

        javax.swing.GroupLayout panel_add_friendLayout = new javax.swing.GroupLayout(panel_add_friend);
        panel_add_friend.setLayout(panel_add_friendLayout);
        panel_add_friendLayout.setHorizontalGroup(
            panel_add_friendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_add_friendLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_add_friendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_add_friendLayout.createSequentialGroup()
                        .addGroup(panel_add_friendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_nameToAdd))
                        .addGap(29, 29, 29)
                        .addComponent(bun_add))
                    .addComponent(l_status_add))
                .addGap(0, 253, Short.MAX_VALUE))
        );
        panel_add_friendLayout.setVerticalGroup(
            panel_add_friendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_add_friendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_add_friendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nameToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bun_add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_status_add)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane_main.addTab("add", panel_add_friend);

        panel_get_ip.setBackground(new java.awt.Color(255, 255, 204));

        jLabel9.setText("friend's name");

        tf_nameForIP.setText(" my friend   ");

        bun_getIP.setText("get ip");
        bun_getIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bun_getIPActionPerformed(evt);
            }
        });

        jLabel10.setText(" ip : ");

        tf_ip_getIP.setText("friends ip");

        l_getIP_status.setText("status");

        javax.swing.GroupLayout panel_get_ipLayout = new javax.swing.GroupLayout(panel_get_ip);
        panel_get_ip.setLayout(panel_get_ipLayout);
        panel_get_ipLayout.setHorizontalGroup(
            panel_get_ipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_get_ipLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_get_ipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_get_ipLayout.createSequentialGroup()
                        .addComponent(l_getIP_status)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_get_ipLayout.createSequentialGroup()
                        .addGroup(panel_get_ipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(panel_get_ipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_get_ipLayout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_ip_getIP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_get_ipLayout.createSequentialGroup()
                                    .addComponent(tf_nameForIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(bun_getIP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(86, 232, Short.MAX_VALUE))))
        );
        panel_get_ipLayout.setVerticalGroup(
            panel_get_ipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_get_ipLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_get_ipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nameForIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bun_getIP))
                .addGap(18, 18, 18)
                .addGroup(panel_get_ipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_ip_getIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(l_getIP_status)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane_main.addTab("get_ip", panel_get_ip);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        panel_users_list.setBackground(new java.awt.Color(255, 204, 204));

        jLabel8.setText("users list");

        ta_ulist.setColumns(20);
        ta_ulist.setRows(5);
        jScrollPane2.setViewportView(ta_ulist);

        javax.swing.GroupLayout panel_users_listLayout = new javax.swing.GroupLayout(panel_users_list);
        panel_users_list.setLayout(panel_users_listLayout);
        panel_users_listLayout.setHorizontalGroup(
            panel_users_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_users_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(64, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panel_users_listLayout.setVerticalGroup(
            panel_users_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_users_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_friends_list.setBackground(new java.awt.Color(255, 204, 204));

        ta_flist.setColumns(20);
        ta_flist.setRows(5);
        jScrollPane1.setViewportView(ta_flist);

        jLabel6.setText("friends list");

        javax.swing.GroupLayout panel_friends_listLayout = new javax.swing.GroupLayout(panel_friends_list);
        panel_friends_list.setLayout(panel_friends_listLayout);
        panel_friends_listLayout.setHorizontalGroup(
            panel_friends_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_friends_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(58, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panel_friends_listLayout.setVerticalGroup(
            panel_friends_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_friends_listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(panel_friends_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_users_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_users_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_friends_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbedPane_main.addTab("friends", jPanel4);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        bun_gchat_tab1_add.setText("JOIN Group");
        bun_gchat_tab1_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bun_gchat_tab1_addActionPerformed(evt);
            }
        });

        ta_gchat_tab1_log.setEditable(false);
        ta_gchat_tab1_log.setLineWrap(true);
        ta_gchat_tab1_log.setEnabled(false);
        jScrollPane8.setViewportView(ta_gchat_tab1_log);

        tf_gchat_tab1_msg.setText(" ");

        bun_gchat_tab1_send.setText("SEND");
        bun_gchat_tab1_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bun_gchat_tab1_sendActionPerformed(evt);
            }
        });

        l_gchat_tab1_status.setText("STATUS");

        ta_gchat_tab1_group.setBackground(new java.awt.Color(204, 255, 204));
        ta_gchat_tab1_group.setText("Group:");

        javax.swing.GroupLayout panel_gchat_tab1Layout = new javax.swing.GroupLayout(panel_gchat_tab1);
        panel_gchat_tab1.setLayout(panel_gchat_tab1Layout);
        panel_gchat_tab1Layout.setHorizontalGroup(
            panel_gchat_tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_gchat_tab1Layout.createSequentialGroup()
                .addGroup(panel_gchat_tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_gchat_tab1Layout.createSequentialGroup()
                        .addComponent(l_gchat_tab1_status, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bun_gchat_tab1_add))
                    .addComponent(ta_gchat_tab1_group, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel_gchat_tab1Layout.createSequentialGroup()
                .addGroup(panel_gchat_tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_gchat_tab1Layout.createSequentialGroup()
                        .addComponent(tf_gchat_tab1_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bun_gchat_tab1_send, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 224, Short.MAX_VALUE))
        );
        panel_gchat_tab1Layout.setVerticalGroup(
            panel_gchat_tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_gchat_tab1Layout.createSequentialGroup()
                .addGroup(panel_gchat_tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_gchat_tab1_status)
                    .addComponent(bun_gchat_tab1_add))
                .addGap(10, 10, 10)
                .addComponent(ta_gchat_tab1_group)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_gchat_tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_gchat_tab1_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bun_gchat_tab1_send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        tabPanel_chat.addTab("tab1", panel_gchat_tab1);

        jScrollPane6.setViewportView(tabPanel_chat);

        jSplitPane1.setRightComponent(jScrollPane6);
        jSplitPane1.setLeftComponent(jLabel7);

        jScrollPane4.setViewportView(jSplitPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        tabbedPane_main.addTab("group chat", jPanel1);

        tf_p2pchat_name.setText(" ");

        bun_p2pchat_getip.setText("validate user");
        bun_p2pchat_getip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bun_p2pchat_getipActionPerformed(evt);
            }
        });

        l_p2pchat_status.setText("STATUS: ");

        ta_p2pchat_log.setColumns(20);
        ta_p2pchat_log.setRows(5);
        jScrollPane10.setViewportView(ta_p2pchat_log);

        tf_p2pchat_msg.setText(" ");

        bun_p2pchat_send.setText("SEND");
        bun_p2pchat_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bun_p2pchat_sendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tf_p2pchat_name, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(bun_p2pchat_getip, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_p2pchat_status, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(tf_p2pchat_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bun_p2pchat_send, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_p2pchat_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bun_p2pchat_getip, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_p2pchat_status, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bun_p2pchat_send, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(tf_p2pchat_msg))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        tabbedPane_main.addTab("p2p chat", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane_main)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane_main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bun_con_serverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bun_con_serverActionPerformed
        // TODO add your handling code here:
        actionPerformed(evt);
    }//GEN-LAST:event_bun_con_serverActionPerformed

    private void bun_disconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bun_disconnectActionPerformed
        actionPerformed(evt);
    }//GEN-LAST:event_bun_disconnectActionPerformed

    private void bun_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bun_loginActionPerformed
        actionPerformed(evt);
    }//GEN-LAST:event_bun_loginActionPerformed

    private void bun_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bun_registerActionPerformed
        // TODO add your handling code here:
        actionPerformed(evt);
    }//GEN-LAST:event_bun_registerActionPerformed

    private void bun_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bun_logoutActionPerformed
        // TODO add your handling code here:
        actionPerformed(evt);
    }//GEN-LAST:event_bun_logoutActionPerformed

    private void bun_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bun_addActionPerformed
        // TODO add your handling code here:
        actionPerformed(evt);
    }//GEN-LAST:event_bun_addActionPerformed

    private void bun_getIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bun_getIPActionPerformed
        actionPerformed(evt);
    }//GEN-LAST:event_bun_getIPActionPerformed

    private void bun_gchat_tab1_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bun_gchat_tab1_addActionPerformed
        // GROUP CHAT ACTION ADD
        //actionPerformed_gchat(evt);
        if( client.p2p_group == null )
        client.sendToServer(new Message(Message.LEADER_gchat,Client.un_loggedin,""));
        else{ JOptionPane.showMessageDialog(null, "already joined"); }
    }//GEN-LAST:event_bun_gchat_tab1_addActionPerformed

    private void bun_gchat_tab1_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bun_gchat_tab1_sendActionPerformed
        // GROUP CHAT ACTION SEND
        //actionPerformed_gchat(evt);
        if(client.p2p_group == null){
            JOptionPane.showMessageDialog(null, "first add yourself to group");
        }else{
            System.out.println("p2p_group:"+client.p2p_group.leader+":"+client.p2p_group.if_group_leader+":"+client.p2p_group.group);
            System.out.println(client.nodes_p2p_connectedTo);
            String msg_gchat=this.tf_gchat_tab1_msg.getText().trim();
            if(msg_gchat.equalsIgnoreCase("") ){msg_gchat=null;}
            if( msg_gchat != null ){
                client.p2p_group.send(Client.un_loggedin, msg_gchat );
                this.set_panel_gchat_tab1(false, "", 3,"me:->"+ msg_gchat+"\n", 0);
            }else{
                JOptionPane.showMessageDialog(null, "null message!");
            }
        }
    }//GEN-LAST:event_bun_gchat_tab1_sendActionPerformed

    private void bun_p2pchat_getipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bun_p2pchat_getipActionPerformed
        // TODO add your handling code here:
        actionPerformed_p2pchat(evt);
    }//GEN-LAST:event_bun_p2pchat_getipActionPerformed

    private void bun_p2pchat_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bun_p2pchat_sendActionPerformed
        // TODO add your handling code here:
        actionPerformed_p2pchat(evt);
    }//GEN-LAST:event_bun_p2pchat_sendActionPerformed

    public void actionPerformed_p2pchat(ActionEvent e){
        Object o = e.getSource();
        System.out.println("p2pchat evt");
        
        if(o==bun_p2pchat_getip ){
            try {
                if( this.tf_p2pchat_name.getText().trim()==null ){}
                else{
                    client.get_ip_p2pchat("", this.tf_p2pchat_name.getText().trim());
                }
            } catch (Exception excp) {
                System.out.println("actionPerformed_gchat bun_gchat_tab1_add excp --/");
            }
            return ;
        }
        if( o== this.bun_p2pchat_send ){
            String s = this.tf_p2pchat_msg.getText().trim();
            
            if(s != null){
                System.out.println("send:"+this.l_p2pchat_status.getText()+":"+s);
                client.send_P2P_connectTo(Client.un_loggedin, this.l_p2pchat_status.getText(), s);
                this.set_panel_p2pchat(false, "", 3, "Me->"+s+"\n", 0);
                this.set_panel_p2pchat(false, "", 0, "", 4);
            }
            return ;
        }
        
    }
    
    
    public void actionPerformed(ActionEvent e) {
        System.out.println("Some gui event!");
	Object o = e.getSource();
        
        String inp1,inp2; int port;
        if(o== this.bun_con_server){
            try {
                this.l_con_status.setText("Connecting...");
                //System.out.println("Connecting...");
                inp1 = this.tf_server_ip.getText().trim();
                inp2 = this.tf_server_port.getText().trim();
                try { port = Integer.valueOf(inp2); //System.out.println("port "+port);
                }catch (Exception excp) {this.l_con_status.setText("actionPerformed excp Non-Integer port No.! --/"); 
                return ;}
                client = new Client(this);
               // System.out.println("client object --/");
                if( client.connectToServer(inp1, port) ){
                //    System.out.println("Connected to server --/");
                    this.notify_connected();
                }else{ client=null; this.l_con_status.setText("Could not connect to: "+inp1 +"/"+port);
                }
               // System.out.println("return bun_con_server --/");
            } catch (Exception excp) {
                System.out.println("bun_con_server excp --/");
            }
            return ;
        }
        if(o == this.bun_disconnect){
            try {
                //this.l_con_status.setText("disconnecting");
                client.disconnect();
                client=null;
                this.notify_disconnect();
            } catch (Exception excp) {
                System.out.println("bun_disconnect excp --/");
            }
        }
        if(o == this.bun_register) {
            //System.out.println("trying to register");
            String u,p;
            u=this.tf_un.getText().trim();
            if(u=="") return ;
            p=this.pf_pass.getText().trim();
            if(p=="") return ;
            client.register(u, p);
            return;
        }
        if(o == this.bun_login) {
           // System.out.println("try login");
            String u,p;
            u=this.tf_un.getText().trim();
            if(u=="") return ;
            p=this.pf_pass.getText().trim();
            if(p=="") return ;
            client.login(u, p);
            return;
        }
	// if it is the Logout button
        if(o == this.bun_logout) {
           // System.out.println("try logout");
            client.logout();
            return;
        }
        if(o == this.bun_add) {
            String inp = this.tf_nameToAdd.getText().trim();
            if( inp == null ) return ;
            client.add_friend("", inp);
            return;
        }
        if(o == this.bun_getIP) {
            String inp = this.tf_nameForIP.getText().trim();
            if( inp == null ) return ;
            client.get_ip("", inp);
            return;
        }
    }
    
    
    public void notify_connected(){ clear(); set_panel_server(false,"connected");  }
    public void notify_disconnect(){clear();default_gui__(); set_panel_server(true,"disconnected"); }
    public void clear(){
        this.ta_flist.setText("");
        this.ta_ulist.setText("");
        this.ta_p2pchat_log.setText("");
        this.ta_gchat_tab1_log.setText("");
    }
    public void default_gui__(){set_panel_server(true,"status"); set_panel_login(true,"status");}
    
    public void notify_registered(){ set_panel_login(true,"User Registered!"); }
    public void notify_reg_failed(){ set_panel_login(true,"failed Registration !"); }
    public void notify_login(){      set_panel_login(false,"User loggedin!"); }
    public void notify_login_fail(){ set_panel_login(true,"failed login!"); }
    public void notify_logout(){     set_panel_login(true,"logged out!"); clear(); }
    public void notify_add_to_list(String f){ set_panel_add_friend("Added:"+f); set_panel_friends_list(true,f); }
    public void notify_add_fail(){            set_panel_add_friend("Failed"); }
    public void notify_getIP(String s){       set_panel_get_ip(s,"found");  }
    public void notify_getIP_fail(){          set_panel_get_ip("","unavailable"); }
    public void notify_friendslist(String s){this.ta_flist.setText(s);}
    public void notify_userslist(String s){this.ta_ulist.setText(s);}
//    public void notify_chatmsg(String s){set_panel_chat_ta(false,s);}
    
    public void set_panel_server(boolean bun_con,String status){
        this.bun_con_server.setVisible(bun_con); 
        this.bun_disconnect.setVisible(!bun_con); 
        this.l_con_status.setText(status);
    }
    public void set_panel_login(boolean b,String status){
        this.bun_login.setVisible(b); 
        this.bun_register.setVisible(b);
        this.bun_logout.setVisible(!b);
        this.l_login_msg.setText(status);
    }
    public void set_panel_add_friend(String status){ 
        this.l_status_add.setText(status);
    }
    public void set_panel_get_ip(String ip,String status){
        this.tf_ip_getIP.setText(ip);
        this.l_getIP_status.setText(status);
    }
    public void set_panel_friends_list(boolean a,String list){
        this.ta_flist.setEditable(false);
        if(a){
            this.ta_flist.append(list);
            this.ta_flist.setCaretPosition(this.ta_flist.getText().length() -1 );
            return ;
        }
        this.ta_flist.setText(list);         
    }
    public void set_panel_users_list(String list){
        this.ta_ulist.setText(list);
        this.ta_flist.setEditable(false);
    }
    public void set_panel_friend_list(String list){
        this.ta_flist.setText(list);
        this.ta_flist.setEditable(false);
    }
    

    public void set_panel_gchat_tab1(boolean change_status,String status, int add_to_ta,String s ,int clear_tf){
        if(change_status){ this.l_gchat_tab1_status.setText(status); }
        switch(add_to_ta){
            case 2: this.ta_gchat_tab1_group.setText(ta_gchat_tab1_group.getText()+" "+ s); break;
            case 3: this.ta_gchat_tab1_log.append(s); break;  
        }
        switch(clear_tf){
            //case 1: this.tf_gchat_tab1_name.setText(""); break;
            case 3: this.ta_gchat_tab1_log.setText(""); break;
            case 4: this.tf_gchat_tab1_msg.setText(""); break;  
        }
    }
    public void notify_getIP_gchat_fail(){ set_panel_gchat_tab1(true,"unavailable",0,"",0); }
    public void notify_getIP_gchat(String ip){ 
        set_panel_gchat_tab1(true,"available",0,"",0);
        //set_panel_gchat_tab1(false,"",2," "+this.tf_gchat_tab1_name.getText().trim(),0);  
    }
    
    public void set_panel_p2pchat(boolean change_status,String status, int add_to_ta,String s ,int clear_tf){
        if(change_status){ this.l_p2pchat_status.setText(status); }
        switch(add_to_ta){
            case 2: this.l_p2pchat_status.setText(s); break;
            case 3: this.ta_p2pchat_log.append(s); break;  
        }
        switch(clear_tf){
            case 1: this.tf_p2pchat_name.setText(""); break;
            case 3: this.ta_p2pchat_log.setText(""); break;
            case 4: this.tf_p2pchat_msg.setText(""); break;  
        }
    }
    public void notify_getIP_p2pchat_fail(){ set_panel_p2pchat(true,"unavailable",0,"",0); }
    public void notify_getIP_p2pchat(String name){ 
        set_panel_p2pchat(true,name,0,"",0);
        
        //this.bun_p2pchat_getip.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bun_add;
    public javax.swing.JButton bun_con_server;
    public javax.swing.JButton bun_disconnect;
    private javax.swing.JButton bun_gchat_tab1_add;
    private javax.swing.JButton bun_gchat_tab1_send;
    public javax.swing.JButton bun_getIP;
    public javax.swing.JButton bun_login;
    public javax.swing.JButton bun_logout;
    private javax.swing.JButton bun_p2pchat_getip;
    private javax.swing.JButton bun_p2pchat_send;
    public javax.swing.JButton bun_register;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JLabel l_con_status;
    private javax.swing.JLabel l_gchat_tab1_status;
    public javax.swing.JLabel l_getIP_status;
    public javax.swing.JLabel l_login_msg;
    private javax.swing.JLabel l_p2pchat_status;
    public javax.swing.JLabel l_status_add;
    public javax.swing.JPanel panel_add_friend;
    public javax.swing.JPanel panel_friends_list;
    private javax.swing.JPanel panel_gchat_tab1;
    public javax.swing.JPanel panel_get_ip;
    public javax.swing.JPanel panel_login;
    public javax.swing.JPanel panel_server;
    public javax.swing.JPanel panel_users_list;
    public javax.swing.JTextField pf_pass;
    public javax.swing.JTextArea ta_flist;
    private javax.swing.JLabel ta_gchat_tab1_group;
    private javax.swing.JTextArea ta_gchat_tab1_log;
    private javax.swing.JTextArea ta_p2pchat_log;
    public javax.swing.JTextArea ta_ulist;
    private javax.swing.JTabbedPane tabPanel_chat;
    private javax.swing.JTabbedPane tabbedPane_main;
    private javax.swing.JTextField tf_gchat_tab1_msg;
    public javax.swing.JTextField tf_ip_getIP;
    public javax.swing.JTextField tf_nameForIP;
    public javax.swing.JTextField tf_nameToAdd;
    private javax.swing.JTextField tf_p2pchat_msg;
    private javax.swing.JTextField tf_p2pchat_name;
    public javax.swing.JTextField tf_server_ip;
    public javax.swing.JTextField tf_server_port;
    public javax.swing.JTextField tf_un;
    // End of variables declaration//GEN-END:variables
}
